version: 0.0.1.{build}-{branch}
init:
- ps: git config --global core.autocrlf true
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\build.cmd --quiet verify
test: off
artifacts:
- path: artifacts\build\Leet.Corelib\Release\Leet.Corelib.*.nupkg
- path: artifacts\build\Leet.Specifications.Corelib\Release\Leet.Specifications.Corelib.*.nupkg
deploy:
- provider: Environment
  name: MyGet
  on:
    LEET_PUSH_NUGET: 1