// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Leet.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal TestResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leet.Tests.Corelib.Properties.TestResources", typeof(TestResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exception was expected but not thrown..
        /// </summary>
        public static string Assert_ExceptionNotThrown {
            get {
                return ResourceManager.GetString("Assert_ExceptionNotThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exception of unexpected type was thrown..
        /// </summary>
        public static string Assert_WrongExceptionThrown {
            get {
                return ResourceManager.GetString("Assert_WrongExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Expected exception has not been thrown..
        /// </summary>
        public static string Exception_InvalidOperation_NoExpectedException {
            get {
                return ResourceManager.GetString("Exception_InvalidOperation_NoExpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Interface method is not supported for this object..
        /// </summary>
        public static string Exceptions_NotSupported_InterfaceMethod {
            get {
                return ResourceManager.GetString("Exceptions_NotSupported_InterfaceMethod", resourceCulture);
            }
        }
    }
}
